Friend Module GameState
    Friend Const Navigation = "Navigation"
    Friend Const MoveUp = "MoveUp"
    Friend Const MoveDown = "MoveDown"
    Friend Const MoveLeft = "MoveLeft"
    Friend Const MoveRight = "MoveRight"
    Friend Const Scanner = "Scanner"
    Friend Const ChangeGalacticAge = "ChangeGalacticAge"
    Friend Const ChangeGalacticDensity = "ChangeGalacticDensity"
    Friend Const Tutorial = "Tutorial"
    Friend Const ActionMenu = "ActionMenu"
    Friend Const EnterStarSystem = "EnterStarSystem"
    Friend Const ApproachPlanet = "ApproachPlanet"
    Friend Const ApproachStar = "ApproachStar"
    Friend Const Dead = "Dead"
    Friend Const RefillOxygen = "RefillOxygen"
    Friend Const Refuel = "Refuel"
    Friend Const StarSystemList = "StarSystemList"
    Friend Const StarSystemDetails = "StarSystemDetails"
End Module
