Friend Module Prompts
    Friend Const ActionMenu = "Action Menu:"
    Friend Const EmbarkMenu = "Embark Menu:"
    Friend Const EquipmentSlot = "Equipment Slot:"
    Friend Const EquippedItem = "Equipped Item:"
    Friend Const FactionCount = "Faction Count:"
    Friend Const GalacticAge = "Galactic Age:"
    Friend Const GalacticDensity = "Galactic Density:"
    Friend Const GameMenu = "Game Menu:"
    Friend Const Inventory = "Inventory:"
    Friend Const LoadGame = "Load Game:"
    Friend Const MainMenu = "Main Menu:"
    Friend Const SaveGame = "Save Game:"
    Friend Const SPLORRPedia = "SPLORR!!Pedia:"
    Friend Const StartingWealth = "Starting Wealth:"
End Module
