Friend Module DialogChoices
    Friend Const AbandonMission = "Abandon Mission"
    Friend Const Accept = "Accept"
    Friend Const Buy = "Buy"
    Friend Const Cancel = "Cancel"
    Friend Const ChangeEquipment = "Change Equipment"
    Friend Const Confirm = "Confirm"
    Friend Const Done = "Done"
    Friend Const InstallEquipment = "Install Equipment"
    Friend Const Ok = "Ok"
    Friend Const RefillFuel = "Refill Fuel"
    Friend Const RefillOxygen = "Refill Oxygen"
    Friend Const Sell = "Sell"
    Friend Const UninstallEquipment = "Uninstall Equipment"
End Module
