Friend Module LegacyStatisticTypes
    Friend ReadOnly ActorId As String = NameOf(ActorId)
    Friend ReadOnly Column As String = NameOf(Column)
    Friend ReadOnly Columns As String = NameOf(Columns)
    Friend ReadOnly CurrentValue As String = NameOf(CurrentValue)
    Friend ReadOnly LocationId As String = NameOf(LocationId)
    Friend ReadOnly MapId As String = NameOf(MapId)
    Friend ReadOnly MaximumValue As String = NameOf(MaximumValue)
    Friend ReadOnly MinimumValue As String = NameOf(MinimumValue)
    Friend ReadOnly ParentId As String = NameOf(ParentId)
    Friend ReadOnly Row As String = NameOf(Row)
    Friend ReadOnly Rows As String = NameOf(Rows)
    Friend ReadOnly TargetLocationId As String = NameOf(TargetLocationId)
    Friend ReadOnly Turn As String = NameOf(Turn)
    Friend ReadOnly WalletId As String = NameOf(WalletId)
End Module
