Friend Module StatisticTypes
    Friend ReadOnly ActorId As String = NameOf(ActorId)
    Friend ReadOnly Authority As String = NameOf(Authority)
    Friend ReadOnly Column As String = NameOf(Column)
    Friend ReadOnly Columns As String = NameOf(Columns)
    Friend ReadOnly Conviction As String = NameOf(Conviction)
    Friend ReadOnly CurrentValue As String = NameOf(CurrentValue)
    Friend ReadOnly Facing As String = NameOf(Facing)
    Friend ReadOnly FactionId As String = NameOf(FactionId)
    Friend ReadOnly Fuel As String = NameOf(Fuel)
    Friend ReadOnly HomePlanetId As String = NameOf(HomePlanetId)
    Friend ReadOnly InteractorId As String = NameOf(InteractorId)
    Friend ReadOnly Jools As String = NameOf(Jools)
    Friend ReadOnly LifeSupportId As String = NameOf(LifeSupportId)
    Friend ReadOnly LocationId As String = NameOf(LocationId)
    Friend ReadOnly MapId As String = NameOf(MapId)
    Friend ReadOnly MaximumFuel As String = NameOf(MaximumFuel)
    Friend ReadOnly MaximumValue As String = NameOf(MaximumValue)
    Friend ReadOnly MinimumJools As String = NameOf(MinimumJools)
    Friend ReadOnly MinimumPlanetCount As String = NameOf(MinimumPlanetCount)
    Friend ReadOnly MinimumValue As String = NameOf(MinimumValue)
    Friend ReadOnly ParentId As String = NameOf(ParentId)
    Friend ReadOnly PlaceId As String = NameOf(PlaceId)
    Friend ReadOnly PlanetCount As String = NameOf(PlanetCount)
    Friend ReadOnly PlanetVicinityCount As String = NameOf(PlanetVicinityCount)
    Friend ReadOnly Row As String = NameOf(Row)
    Friend ReadOnly Rows As String = NameOf(Rows)
    Friend ReadOnly SatelliteCount As String = NameOf(SatelliteCount)
    Friend ReadOnly Standards As String = NameOf(Standards)
    Friend ReadOnly TargetLocationId As String = NameOf(TargetLocationId)
    Friend ReadOnly Turn As String = NameOf(Turn)
    Friend ReadOnly VesselId As String = NameOf(VesselId)
    Friend ReadOnly WalletId As String = NameOf(WalletId)
    Friend ReadOnly WormholeDestinationId As String = NameOf(WormholeDestinationId)
    Friend ReadOnly X As String = NameOf(X)
    Friend ReadOnly Y As String = NameOf(Y)

End Module
