Friend Module StatisticTypes
    Friend Const ActorId = "ActorId"
    Friend Const AvatarId = "AvatarId"
    Friend Const Column = "Column"
    Friend Const Columns = "Columns"
    Friend Const Facing = "Facing"
    Friend Const Fuel = "Fuel"
    Friend Const Jools = "Jools"
    Friend Const LocationId = "LocationId"
    Friend Const MapId = "MapId"
    Friend Const MaximumFuel = "MaximumFuel"
    Friend Const MaximumOxygen = "MaximumOxygen"
    Friend Const MinimumJools = "MinimumJools"
    Friend Const Oxygen = "Oxygen"
    Friend Const PlanetId = "PlanetId"
    Friend Const PlanetVicinityId = "PlanetVicinityId"
    Friend Const Row = "Row"
    Friend Const Rows = "Rows"
    Friend Const SatelliteId = "SatelliteId"
    Friend Const StarId = "StarId"
    Friend Const StarSystemId = "StarSystemId"
    Friend Const StarVicinityId = "StarVicinityId"
    Friend Const TeleporterId = "TeleporterId"
    Friend Const Turn = "Turn"
End Module
